#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExplosiveDamage_FW_knockback

#include "Basic.hpp"

#include "FWGameCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ExplosiveDamage_FW_knockback.BP_ExplosiveDamage_FW_knockback_C
// 0x0000 (0x0040 - 0x0040)
class UBP_ExplosiveDamage_FW_knockback_C final : public UFWKnockDownDamageType
{
public:
	void GetCanDieFrom();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExplosiveDamage_FW_knockback_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExplosiveDamage_FW_knockback_C")
	}
	static class UBP_ExplosiveDamage_FW_knockback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ExplosiveDamage_FW_knockback_C>();
	}
};

}

