#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Interface_LevelInformation

#include "Basic.hpp"

#include "BP_Interface_LevelInformation_classes.hpp"
#include "BP_Interface_LevelInformation_parameters.hpp"


namespace SDK
{

// Function BP_Interface_LevelInformation.BP_Interface_LevelInformation_C.GetLevelInformation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TimeRemaining                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           BackPackRig_s_                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   GameStatus                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LootCollectionCount                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LootCollectionRequired                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CanExtract                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBP_Interface_LevelInformation_C::GetLevelInformation(int32 TimeRemaining, class UClass* BackPackRig_s_, int32 GameStatus, int32 LootCollectionCount, int32 LootCollectionRequired, bool CanExtract)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BP_Interface_LevelInformation_C", "GetLevelInformation");

	Params::BP_Interface_LevelInformation_C_GetLevelInformation Parms{};

	Parms.TimeRemaining = TimeRemaining;
	Parms.BackPackRig_s_ = BackPackRig_s_;
	Parms.GameStatus = GameStatus;
	Parms.LootCollectionCount = LootCollectionCount;
	Parms.LootCollectionRequired = LootCollectionRequired;
	Parms.CanExtract = CanExtract;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

