#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lamp_Medical_D

#include "Basic.hpp"

#include "BP_Lamp_Medical_D_classes.hpp"
#include "BP_Lamp_Medical_D_parameters.hpp"


namespace SDK
{

// Function BP_Lamp_Medical_D.BP_Lamp_Medical_D_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Lamp_Medical_D_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lamp_Medical_D_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

