#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Quest_DecDemo_Task_030_LootBags

#include "Basic.hpp"

#include "BP_Quest_DecDemo_Task_030_LootBags_classes.hpp"
#include "BP_Quest_DecDemo_Task_030_LootBags_parameters.hpp"


namespace SDK
{

// Function BP_Quest_DecDemo_Task_030_LootBags.BP_Quest_DecDemo_Task_030_LootBags_C.ExecuteUbergraph_BP_Quest_DecDemo_Task_030_LootBags
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Quest_DecDemo_Task_030_LootBags_C::ExecuteUbergraph_BP_Quest_DecDemo_Task_030_LootBags(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Quest_DecDemo_Task_030_LootBags_C", "ExecuteUbergraph_BP_Quest_DecDemo_Task_030_LootBags");

	Params::BP_Quest_DecDemo_Task_030_LootBags_C_ExecuteUbergraph_BP_Quest_DecDemo_Task_030_LootBags Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Quest_DecDemo_Task_030_LootBags.BP_Quest_DecDemo_Task_030_LootBags_C.OnQuestTaskCompleted
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Owner                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UQuest>               ParentQuest                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UBP_Quest_DecDemo_Task_030_LootBags_C::OnQuestTaskCompleted(class AActor* Owner, TSubclassOf<class UQuest> ParentQuest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Quest_DecDemo_Task_030_LootBags_C", "OnQuestTaskCompleted");

	Params::BP_Quest_DecDemo_Task_030_LootBags_C_OnQuestTaskCompleted Parms{};

	Parms.Owner = Owner;
	Parms.ParentQuest = ParentQuest;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Quest_DecDemo_Task_030_LootBags.BP_Quest_DecDemo_Task_030_LootBags_C.OnQuestTaskFailed
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Owner                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UQuest>               ParentQuest                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UBP_Quest_DecDemo_Task_030_LootBags_C::OnQuestTaskFailed(class AActor* Owner, TSubclassOf<class UQuest> ParentQuest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Quest_DecDemo_Task_030_LootBags_C", "OnQuestTaskFailed");

	Params::BP_Quest_DecDemo_Task_030_LootBags_C_OnQuestTaskFailed Parms{};

	Parms.Owner = Owner;
	Parms.ParentQuest = ParentQuest;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Quest_DecDemo_Task_030_LootBags.BP_Quest_DecDemo_Task_030_LootBags_C.OnQuestTaskStarted
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Owner                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UQuest>               ParentQuest                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UBP_Quest_DecDemo_Task_030_LootBags_C::OnQuestTaskStarted(class AActor* Owner, TSubclassOf<class UQuest> ParentQuest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Quest_DecDemo_Task_030_LootBags_C", "OnQuestTaskStarted");

	Params::BP_Quest_DecDemo_Task_030_LootBags_C_OnQuestTaskStarted Parms{};

	Parms.Owner = Owner;
	Parms.ParentQuest = ParentQuest;

	UObject::ProcessEvent(Func, &Parms);
}

}

