#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmokeThrowable

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Throwable_Object_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SmokeThrowable.BP_SmokeThrowable_C
// 0x0010 (0x0320 - 0x0310)
class ABP_SmokeThrowable_C final : public ABP_Throwable_Object_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SmokeThrowable_C;                // 0x0310(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        Detonation_Time;                                   // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_SmokeThrowable(int32 EntryPoint);
	void OnExplosion();
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void Velocity_Check();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SmokeThrowable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SmokeThrowable_C")
	}
	static class ABP_SmokeThrowable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SmokeThrowable_C>();
	}
};

}

