#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_Lordoss_RandomPatrolPoint

#include "Basic.hpp"

#include "BTT_Lordoss_RandomPatrolPoint_classes.hpp"
#include "BTT_Lordoss_RandomPatrolPoint_parameters.hpp"


namespace SDK
{

// Function BTT_Lordoss_RandomPatrolPoint.BTT_Lordoss_RandomPatrolPoint_C.ExecuteUbergraph_BTT_Lordoss_RandomPatrolPoint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTT_Lordoss_RandomPatrolPoint_C::ExecuteUbergraph_BTT_Lordoss_RandomPatrolPoint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTT_Lordoss_RandomPatrolPoint_C", "ExecuteUbergraph_BTT_Lordoss_RandomPatrolPoint");

	Params::BTT_Lordoss_RandomPatrolPoint_C_ExecuteUbergraph_BTT_Lordoss_RandomPatrolPoint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTT_Lordoss_RandomPatrolPoint.BTT_Lordoss_RandomPatrolPoint_C.Find Markup (if any)
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Found_valid_markup_                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTT_Lordoss_RandomPatrolPoint_C::Find_Markup__if_any_(bool* Found_valid_markup_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTT_Lordoss_RandomPatrolPoint_C", "Find Markup (if any)");

	Params::BTT_Lordoss_RandomPatrolPoint_C_Find_Markup__if_any_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Found_valid_markup_ != nullptr)
		*Found_valid_markup_ = Parms.Found_valid_markup_;
}


// Function BTT_Lordoss_RandomPatrolPoint.BTT_Lordoss_RandomPatrolPoint_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBTT_Lordoss_RandomPatrolPoint_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTT_Lordoss_RandomPatrolPoint_C", "ReceiveExecuteAI");

	Params::BTT_Lordoss_RandomPatrolPoint_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}

}

