#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_OverTheHead_GunHead

#include "Basic.hpp"

#include "GA_OverTheHead_GunHead_classes.hpp"
#include "GA_OverTheHead_GunHead_parameters.hpp"


namespace SDK
{

// Function GA_OverTheHead_GunHead.GA_OverTheHead_GunHead_C.CheckForReload
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_OverTheHead_GunHead_C::CheckForReload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverTheHead_GunHead_C", "CheckForReload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_OverTheHead_GunHead.GA_OverTheHead_GunHead_C.ExecuteUbergraph_GA_OverTheHead_GunHead
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_OverTheHead_GunHead_C::ExecuteUbergraph_GA_OverTheHead_GunHead(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverTheHead_GunHead_C", "ExecuteUbergraph_GA_OverTheHead_GunHead");

	Params::GA_OverTheHead_GunHead_C_ExecuteUbergraph_GA_OverTheHead_GunHead Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_OverTheHead_GunHead.GA_OverTheHead_GunHead_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_OverTheHead_GunHead_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverTheHead_GunHead_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_OverTheHead_GunHead.GA_OverTheHead_GunHead_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_OverTheHead_GunHead_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_OverTheHead_GunHead_C", "K2_OnEndAbility");

	Params::GA_OverTheHead_GunHead_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}

}

