#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Player_Dodge

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FWGameCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Player_Dodge.GA_Player_Dodge_C
// 0x0018 (0x03D0 - 0x03B8)
class UGA_Player_Dodge_C final : public UFWGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   Section_Name;                                      // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           DiveMontage;                                       // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Player_Dodge(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void K2_OnEndAbility(bool bWasCancelled);
	void OnBlendOut_7698200B4E6CC3A0FCF1E288E90276DD();
	void OnCancelled_7698200B4E6CC3A0FCF1E288E90276DD();
	void OnCompleted_7698200B4E6CC3A0FCF1E288E90276DD();
	void OnInterrupted_7698200B4E6CC3A0FCF1E288E90276DD();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Player_Dodge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Player_Dodge_C")
	}
	static class UGA_Player_Dodge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Player_Dodge_C>();
	}
};

}

