#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Player_InteractSequence

#include "Basic.hpp"

#include "GA_Player_InteractSequence_classes.hpp"
#include "GA_Player_InteractSequence_parameters.hpp"


namespace SDK
{

// Function GA_Player_InteractSequence.GA_Player_InteractSequence_C.ExecuteUbergraph_GA_Player_InteractSequence
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Player_InteractSequence_C::ExecuteUbergraph_GA_Player_InteractSequence(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Player_InteractSequence_C", "ExecuteUbergraph_GA_Player_InteractSequence");

	Params::GA_Player_InteractSequence_C_ExecuteUbergraph_GA_Player_InteractSequence Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Player_InteractSequence.GA_Player_InteractSequence_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Player_InteractSequence_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Player_InteractSequence_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

