#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Fire_AI_RFL01B

#include "Basic.hpp"

#include "FWGameCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Fire_AI_RFL01B.GCN_Fire_AI_RFL01B_C
// 0x0008 (0x0358 - 0x0350)
class UGCN_Fire_AI_RFL01B_C final : public UFWGameplayCueNotify_Burst
{
public:
	class USoundBase*                             SB_RFL01B;                                         // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void OnBurst(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FGameplayCueNotify_SpawnResult& SpawnResults) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Fire_AI_RFL01B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Fire_AI_RFL01B_C")
	}
	static class UGCN_Fire_AI_RFL01B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Fire_AI_RFL01B_C>();
	}
};

}

