#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Global_6

#include "Basic.hpp"

#include "FWGameCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Global_6.GE_Global_6_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Global_6_C final : public UFWGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Global_6_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Global_6_C")
	}
	static class UGE_Global_6_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Global_6_C>();
	}
};

}

