#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScavOptions

#include "Basic.hpp"

#include "WBP_ScavOptions_classes.hpp"
#include "WBP_ScavOptions_parameters.hpp"


namespace SDK
{

// Function WBP_ScavOptions.WBP_ScavOptions_C.AddScavOption
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFWScavBuddyButton*               ScavButton                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ScavOptions_C::AddScavOption(class UFWScavBuddyButton* ScavButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "AddScavOption");

	Params::WBP_ScavOptions_C_AddScavOption Parms{};

	Parms.ScavButton = ScavButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.BndEvt__WBP_ScavOptions_UseScavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ScavOptions_C::BndEvt__WBP_ScavOptions_UseScavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "BndEvt__WBP_ScavOptions_UseScavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.CanScroll
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_ScavOptions_C::CanScroll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "CanScroll");

	Params::WBP_ScavOptions_C_CanScroll Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ScavOptions_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.DeSelect
// (BlueprintCallable, BlueprintEvent)

void UWBP_ScavOptions_C::DeSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "DeSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.ExecuteUbergraph_WBP_ScavOptions
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ScavOptions_C::ExecuteUbergraph_WBP_ScavOptions(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "ExecuteUbergraph_WBP_ScavOptions");

	Params::WBP_ScavOptions_C_ExecuteUbergraph_WBP_ScavOptions Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.RefreshPanel
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_ScavOptions_C::RefreshPanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "RefreshPanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.Selected_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_ScavBuddyButton_C*           ScavButton                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_ScavOptions_C::Selected_Event(class UWBP_ScavBuddyButton_C* ScavButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "Selected_Event");

	Params::WBP_ScavOptions_C_Selected_Event Parms{};

	Parms.ScavButton = ScavButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ScavOptions.WBP_ScavOptions_C.TriggerInput
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FKeyEvent&                 Input                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_ScavOptions_C::TriggerInput(const struct FKeyEvent& Input)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ScavOptions_C", "TriggerInput");

	Params::WBP_ScavOptions_C_TriggerInput Parms{};

	Parms.Input = std::move(Input);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

