#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TwoTitleBlackButton

#include "Basic.hpp"

#include "WBP_TwoTitleButton_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TwoTitleBlackButton.WBP_TwoTitleBlackButton_C
// 0x0000 (0x0A30 - 0x0A30)
class UWBP_TwoTitleBlackButton_C final : public UWBP_TwoTitleButton_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_TwoTitleBlackButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_TwoTitleBlackButton_C")
	}
	static class UWBP_TwoTitleBlackButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TwoTitleBlackButton_C>();
	}
};

}

