#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_KeypadDigitWidget

#include "Basic.hpp"

#include "ForeverWinter_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_KeypadDigitWidget.WBP_KeypadDigitWidget_C
// 0x0008 (0x0360 - 0x0358)
class UWBP_KeypadDigitWidget_C final : public UFWKeypadDigitWidget
{
public:
	class UImage*                                 backing;                                           // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_KeypadDigitWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_KeypadDigitWidget_C")
	}
	static class UWBP_KeypadDigitWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_KeypadDigitWidget_C>();
	}
};

}

